package bai3.apps;

public enum Option {
	EXIT, ADD_USER, ADD_NEWS, ADD_COMMENT, GET_NEWS, GET_COMMENT, GET_USER, GET_ALL_NEWS, GET_ALL_COMMENT, GET_ALL_USER,
	UPDATE_NEWS, UPDATE_COMMENT, UPDATE_USER, DELETE_NEWS, DELETE_COMMENT, DELETE_USER,
	GET_NEWS_BY_TAGS_OR_NEWS_CATEGORIES,GET_STATISTIC_USER;
}
