package bai4.apps;

public enum Options {
	EXIT, ADD_EMPLOYEE, REMOVE_EMPLOYEE, UPDATE_EMPLOYEE, GET_EMPLOYEE,
	GET_ALL_EMPLOYEES, ADD_PROJECT, REMOVE_PROJECT, UPDATE_PROJECT, GET_PROJECT,
	GET_ALL_PROJECTS, ADD_EMPLOYEE_PROJECT, REMOVE_EMPLOYEE_PROJECT,
	UPDATE_EMPLOYEE_PROJECT, GET_EMPLOYEE_PROJECT, GET_ALL_EMPLOYEE_PROJECTS, 
	GET_PROJECT_NAME, GET_ALL_PROJECTS_EMAIL, GET_EMPLOYEE_NAME, GET_STATISTIC;
}
